services:
  hazelcast:
    image: hazelcast/hazelcast:5-jdk21
    ports:
      - "5701:5701"
    networks:
      - hazelcast-network  # Custom network for container communication
  management-center:
    image: hazelcast/management-center:6.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
    networks:
      - hazelcast-network  # Same network for proper communication

networks:
  hazelcast-network:
    driver: bridge